### PR TITLE
welcome animation feels painfully slow

### PR DESCRIPTION
**Pull request by InternetRamen**
The welcome page takes around 8 seconds to load right now. IDK if it's artistically intended, but I just wanted to help out in some way.

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
Shortening it a bit might help, however I feel like it adds some character to the website. The website is fully loaded and scrollable at that point; it just takes extra time to animate in.

**Comment by YodaLightsabr** [comment]
I think 2 would work!

**Comment by InternetRamen** [comment]
2 definitely looks better.

**Comment by YodaLightsabr** [comment]
Great!

**Pull request merged**
